### ISSUE TITLE
lqr控制运行问题

### ISSUE THREAD

**Issue by clqr0909** [JoveH-H/path-following-control#1]
from controller import lqr
这一行出现问题：Import "controller" could not be resolved
运行终端显示：cannot import name 'particle' from 'model'
请问该如何解决

**Comment by JoveH-H** [comment]
请问执行了哪个文件呢

**Comment by clqr0909** [comment]
> 
examples里面的
lqr_control.py这个文件

**Comment by JoveH-H** [comment]
这边测试了在不同位置执行该文件都可以的

**Comment by clqr0909** [comment]
> 这边测试了在不同位置执行该文件都可以的

controller这个文件我加了之后程序没有问题，但是运行的结果显示cannot import name 'particle' from 'model'

**Comment by clqr0909** [comment]
> 这边测试了在不同位置执行该文件都可以的

我的好像不是从文件夹中导入.py文件，那如果要直接用的话前面的两句from该怎么修改

**Comment by clqr0909** [comment]
> 这边测试了在不同位置执行该文件都可以的

我把前面的from删掉了，好像可以运行了，谢谢

**Comment by JoveH-H** [comment]
好的呢
